---
book_repo: pivotal-cf/docs-book-stemcell-rn
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: master

feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:
- repository:
    name: pivotal-cf/docs-stemcell-rn
    ref: 'master'
  directory: platform/stemcells
  subnav_template: pcf-subnav.erb
  product_info:
    use_local_header: true
    latest_stable_version: '2.7'
    changelog_href: https://docs.pivotal.io/platform/2-8/stemcells/
    local_header_img: /images/cloud_rings.png
    local_header_title: Pivotal Platform
    search_placeholder: Search Pivotal Platform Stemcell Release Notes
    local_product_version: '2.8'
    url_prefix: platform/stemcells
    local_header_links:
      - <a href="https://network.pivotal.io/">Download</a>
      - <a href="https://support.pivotal.io/hc/en-us/requests/new">Ask for Help</a>
      - <a href="https://community.pivotal.io/s/topic/0TO0P000000IKhwWAG/welcome">Pivotal Support Community</a>
      - <a href="https://resources.docs.pivotal.io/pdfs/pcf-docs-2.6.pdf">PDF</a>
    local_header_version_list:
      - url_prefix: https://docs.pivotal.io/platform/2-7/stemcells
        display_name: v2.7
      - url_prefix: https://docs.pivotal.io/pivotalcf/2-6/stemcells
        display_name: v2.6
      - url_prefix: https://docs.pivotal.io/pivotalcf/2-5/stemcells
        display_name: v2.5
      - url_prefix: https://docs.pivotal.io/pivotalcf/2-4/stemcells
        display_name: v2.4
      - url_prefix: https://docs.pivotal.io/pivotalcf/2-3/stemcells
        display_name: v2.3
      - url_prefix: https://docs.pivotal.io/pivotalcf/2-2/stemcells
        display_name: v2.2
      - url_prefix: https://docs.pivotal.io/pivotalcf/2-1/stemcells
        display_name: v2.1
      - url_prefix: https://docs.pivotal.io/pivotalcf/2-0/stemcells
        display_name: v2.0
      - url_prefix: https://docs.pivotal.io/pivotalcf/1-12/stemcells
        display_name: v1.12
      - url_prefix: https://docs.pivotal.io/pivotalcf/1-11/stemcells
        display_name: v1.11
      - url_prefix: https://docs.pivotal.io/pivotalcf/1-10/stemcells
        display_name: v1.10
      - url_prefix: https://docs.pivotal.io/pivotalcf/1-9/stemcells
        display_name: v1.9
      - <a href="https://resources.docs.pivotal.io/pdfs/pcf-docs-1.8.pdf">v1.8</a>

- repository:
    name: pivotal-cf/docs-partials
  directory: pcf
  no_docs: true
